/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorchat;

import conexaodb.ConexaoDbUsuario;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.IOException;
import java.net.InetAddress;
import java.net.ServerSocket;
import java.util.ArrayList;
import java.util.HashMap;
import modelos.Usuario;

/**
 *
 * @author arcn
 */
public class TelaServer extends javax.swing.JFrame implements WindowListener{

    /**
     * Creates new form TelaServer
     */
    
    public static HashMap<String, Usuario> tabelaUsuarios;
    public static ArrayList<Usuario> listaContatos;
    
    public static Registrador registrador;
    
    public TelaServer() {
        setLocationRelativeTo(null);
        initComponents();
        this.addWindowListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
       
        
        // Instancia a tabela de usuarios
        tabelaUsuarios = new HashMap<>();
        listaContatos = new ArrayList<>();
        
        // Busca a tabela de usuarios cadastrados no servidor: 
        //ConexaoDbUsuario conexao = new ConexaoDbUsuario();
        //tabelaUsuarios = conexao.pegaTodosUsuarios();
       
        
        // Carregamento das classes de controle: 
        Distribuidor distribuidor = new Distribuidor(tabelaUsuarios);
        ServerSocket serverSocket = new ServerSocket(5051);
        
        //serverSocket.bind(new InetSocketAddress("192.168.0.1", 0));
        InetAddress inet = serverSocket.getInetAddress();
        System.out.println("Servidor em: " + inet.getHostName());
        
        
        registrador = new Registrador(distribuidor, serverSocket);
        Thread pilha = new Thread(registrador);
        pilha.start();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaServer().setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        
    }

    @Override
    public void windowClosing(WindowEvent e) {
        System.out.println("Fechou");
        registrador.isRuning = false;
    }

    @Override
    public void windowClosed(WindowEvent e) {

    }

    @Override
    public void windowIconified(WindowEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
         //To change body of generated methods, choose Tools | Templates.
    }
}
